/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aqELJCv6oQHukXP7LyJB9g

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsySi8C91Sj4Ue } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ySi8c91SJ4UE/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsySi8C91Sj4Ue
});
